apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-cicd-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-native-cicd
  template:
    metadata:
      labels:
        app: cloud-native-cicd
    spec:
      containers:
        - name: app
          image: ghcr.io/YOUR_USERNAME/cloud-native-cicd-platform:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "dev"
