apiVersion: v1
kind: Service
metadata:
  name: cloud-native-cicd-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: cloud-native-cicd
  ports:
    - port: 80
      targetPort: 8000
